
#ifndef CURS_CURTYPES_H
#define CURS_CURTYPES_H

#define FIGURE_UNDEFINED -1
#define FIGURE_CUBE 0
#define FIGURE_SPHERE 1
#define FIGURE_PYRAMID 2
#define FIGURE_CYLINDER 3

#define DEFAULT_FIGURE_COLOR ("#FFFFFF")
#define DEFAULT_TRAJECTORY_COLOR ("#111111")
#define DEFAULT_CUBE_EDGE_LENGTH 50
#define DEFAULT_SPHERE_RADIUS_LENGTH 50
#define DEFAULT_SLICES 10
#define DEFAULT_STACKS 10
#define DEFAULT_CYLINDER_BASE_RADIUS 50
#define DEFAULT_CYLINDER_HEIGHT 50
#define DEFAULT_TETRADER_HEIGHT 50
#define DEFAULT_BASE_SPHERE_RADIUS 100
#endif //CURS_CURTYPES_H
